# Generated by Django 5.2.3 on 2025-06-19 22:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome do Prémio')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('probability_weight', models.PositiveIntegerField(default=1, help_text='Um número maior aumenta a chance relativa de ganhar este prémio. Ex: um prémio com peso 2 tem o dobro da chance de um com peso 1.', verbose_name='Peso de Probabilidade')),
                ('is_active', models.BooleanField(default=True, help_text='Se desmarcado, este prémio não poderá ser ganho, mesmo que a roda esteja ativa.', verbose_name='Prémio Ativo?')),
                ('quantity', models.PositiveIntegerField(blank=True, help_text='Opcional: Deixe em branco para quantidade ilimitada. Se um número for definido, diminui a cada vez que é ganho.', null=True, verbose_name='Quantidade Disponível')),
            ],
            options={
                'verbose_name': 'Prémio',
                'verbose_name_plural': 'Prémios',
                'ordering': ['-probability_weight', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PrizeWheelConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Controla se a funcionalidade da Roda da Sorte está globalmente ativa.', verbose_name='Roda da Sorte Ativa?')),
                ('attempts_per_ip_daily', models.PositiveIntegerField(default=3, help_text='Número máximo de vezes que um único IP pode girar a roda por dia.', verbose_name='Tentativas por IP (Diário)')),
            ],
            options={
                'verbose_name': 'Configuração da Roda da Sorte',
                'verbose_name_plural': 'Configurações da Roda da Sorte',
            },
        ),
        migrations.CreateModel(
            name='SpinAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(verbose_name='Endereço IP')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Data/Hora da Tentativa')),
                ('winner_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email do Vencedor')),
                ('prize_won', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='prize_wheel.prize', verbose_name='Prémio Ganho')),
            ],
            options={
                'verbose_name': 'Tentativa na Roda',
                'verbose_name_plural': 'Tentativas na Roda',
                'ordering': ['-timestamp'],
            },
        ),
    ]
