# Generated by Django 5.2.3 on 2025-06-19 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prize_wheel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prizewheelconfig',
            name='overall_win_chance',
            field=models.DecimalField(decimal_places=3, default=0.5, help_text='A probabilidade percentual de um usuário ganhar QUALQUER prémio numa tentativa. Ex: 0.5 para 0.5% de chance (1 em 200). Max 100.', max_digits=5, verbose_name='Chance Geral de Ganhar (%)'),
        ),
    ]
