# Generated by Django 5.2.3 on 2025-06-19 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prize_wheel', '0002_prizewheelconfig_overall_win_chance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spinattempt',
            name='winner_email',
            field=models.EmailField(blank=True, help_text='Email coletado se o usuário ganhar um prémio.', max_length=255, null=True, verbose_name='Email do Vencedor'),
        ),
    ]
