# Generated by Django 5.2.3 on 2025-06-14 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coupon',
            options={'ordering': ['-created_at'], 'verbose_name': 'Cupom', 'verbose_name_plural': 'Cupons'},
        ),
        migrations.AlterField(
            model_name='coupon',
            name='coupon_code',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Código do Cupom'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='direct_link',
            field=models.URLField(blank=True, null=True, verbose_name='Link Direto'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='expiry_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Validade'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='has_expiry',
            field=models.BooleanField(default=False, verbose_name='Tem data de validade?'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Ativo?'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='product_link',
            field=models.URLField(blank=True, null=True, verbose_name='Link do Produto'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='product_name',
            field=models.CharField(max_length=200, verbose_name='Nome do Produto'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualizado em'),
        ),
    ]
