# Generated by Django 5.2.3 on 2025-06-14 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0003_coupon_created_by_coupon_updated_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='click_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Número de Cliques'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='discount_amount',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Valor do Desconto (%)'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='instructions',
            field=models.TextField(blank=True, null=True, verbose_name='Instruções de Uso'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='product_image',
            field=models.ImageField(blank=True, null=True, upload_to='coupons/products/', verbose_name='Imagem do Produto'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='terms',
            field=models.TextField(blank=True, null=True, verbose_name='Termos e Condições'),
        ),
    ]
