# Generated by Django 5.2.3 on 2025-06-14 23:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('coupons', '0004_coupon_click_count_coupon_discount_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coupons', to='categories.category', verbose_name='Categoria'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='views_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Visualizações'),
        ),
    ]
