# Generated by Django 5.2.3 on 2025-06-14 21:27

from django_ckeditor_5.fields import CKEditor5Field
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VPN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=120)),
                ('logo', models.URLField(blank=True, null=True)),
                ('logo_upload', models.ImageField(blank=True, null=True, upload_to='vpn_logos/')),
                ('devices_supported', models.JSONField(default=list)),
                ('keep_logs', models.BooleanField(default=False)),
                ('based_country', models.CharField(max_length=100)),
                ('pros', models.TextField()),
                ('cons', models.TextField()),
                ('num_servers', models.PositiveIntegerField()),
                ('price', models.CharField(max_length=50)),
                ('affiliate_link', models.URLField(blank=True, null=True)),
                ('show_on_homepage', models.BooleanField(default=False)),
                ('overall_rating', models.DecimalField(decimal_places=1, max_digits=3)),
                ('security_rating', models.DecimalField(decimal_places=1, max_digits=3)),
                ('privacy_rating', models.DecimalField(decimal_places=1, max_digits=3)),
                ('speed_rating', models.DecimalField(decimal_places=1, max_digits=3)),
                ('streaming_rating', models.DecimalField(decimal_places=1, max_digits=3)),
                ('torrenting_rating', models.DecimalField(decimal_places=1, max_digits=3)),
                ('additional_features_rating', models.DecimalField(decimal_places=1, max_digits=3)),
                ('device_compatibility_rating', models.DecimalField(decimal_places=1, max_digits=3)),
                ('server_locations_rating', models.DecimalField(decimal_places=1, max_digits=3)),
                ('user_experience_rating', models.DecimalField(decimal_places=1, max_digits=3)),
                ('speeds_by_country', models.JSONField(default=dict, help_text="e.g. {'Germany': 300, 'Portugal': 430}")),
                ('full_review', CKEditor5Field(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categories', models.ManyToManyField(related_name='vpns', to='categories.category')),
            ],
        ),
    ]
