# Generated by Django 5.2.3 on 2025-06-15 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpn', '0002_vpn_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vpn',
            name='cons',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vpn',
            name='pros',
            field=models.TextField(blank=True, null=True),
        ),
    ]
