# Generated by Django 5.2.3 on 2025-06-19 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpn', '0003_alter_vpn_cons_alter_vpn_pros'),
    ]

    operations = [
        migrations.CreateModel(
            name='VPNSpeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100, verbose_name='País')),
                ('speed', models.CharField(help_text="Ex: 300 Mbps ou 'N/A'", max_length=50, verbose_name='Velocidade (Mbps)')),
                ('vpn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='country_speeds', to='vpn.vpn')),
            ],
            options={
                'verbose_name': 'Velocidade por País',
                'verbose_name_plural': 'Velocidades por País',
                'unique_together': {('vpn', 'country')},
            },
        ),
    ]
