"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv

# Carrega as variáveis de ambiente do arquivo .env
load_dotenv()

def get_env_variable(var_name, default=None):
    """
    Obtém o valor de uma variável de ambiente.
    - Se a variável estiver definida e não vazia, retorna seu valor.
    - Se a variável não estiver definida ou estiver vazia:
        - Se um 'default' for fornecido, retorna o 'default'.
        - Se nenhum 'default' for fornecido, levanta ValueError.
    """
    value = os.getenv(var_name)

    if value is None or value == "":  # Not set OR set to an empty string
        if default is not None:
            return default
        else:
            if value is None:
                raise ValueError(
                    f"A variável de ambiente '{var_name}' não está definida e nenhum valor padrão foi fornecido."
                )
            else:  # value == ""
                raise ValueError(
                    f"A variável de ambiente '{var_name}' está definida como uma string vazia e nenhum valor padrão foi fornecido para substituí-la."
                )
    return value # Variable was set and not empty

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Site Name (used for SEO defaults, etc.)
SITE_NAME = 'My Awesome Site'

# Static and media files
STATIC_URL = '/static/'
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# Configurações de Segurança
SECRET_KEY = get_env_variable('SECRET_KEY', 'django-insecure-dev-key-only-for-local')

# Debug e Hosts
# Linha original comentada para diagnóstico
# DEBUG = get_env_variable('DEBUG', 'False').lower() == 'true'

# Teste de diagnóstico: Ativar o DEBUG para ver o erro completo. ISTO É INSEGURO!
DEBUG = True
# Linha original comentada para diagnóstico
# ALLOWED_HOSTS = get_env_variable('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')

# Teste de diagnóstico: Adicionar o IP diretamente para isolar o problema
ALLOWED_HOSTS = ['157.180.91.10', 'localhost', '127.0.0.1']

# Configurações de Sessão Segura
SESSION_COOKIE_SECURE = not DEBUG  # True em produção
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_HTTPONLY = True
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'DENY'

# Configurações de HTTPS (ativar em produção)
SECURE_SSL_REDIRECT = get_env_variable('ENABLE_HTTPS', 'False').lower() == 'true'
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
SECURE_HSTS_SECONDS = 31536000  # 1 ano
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_HSTS_PRELOAD = True


# Tailwind CSS configuration
TAILWIND_APP_NAME = 'theme'
INTERNAL_IPS = [
    "127.0.0.1",
]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'django.contrib.sites',

    # Third-party (always available)
    'tailwind',                 # Added here
    'django_browser_reload',
    'axes',
    'django_ckeditor_5',
    'django_celery_beat',
    'colorfield',

    # Project apps
    'theme',                    # Added here
    'vpn',
    'categories',
    'coupons',
    'blog',
    'analytics',
    'dashboard',
    'settings',
    'custompages',
]

# Conditional logic for Tailwind removed as it's now added directly

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.middleware.gzip.GZipMiddleware',
    'core.middleware.SecurityHeadersMiddleware',
    'axes.middleware.AxesMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'analytics.middleware.AnalyticsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'core.context_processors.settings_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Usando SQLite como banco de dados padrão
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Configuração para PostgreSQL (opcional, caso queira usar em produção)
if get_env_variable('USE_POSTGRES', 'False').lower() == 'true':
    DATABASES['default'] = {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': get_env_variable('DB_NAME', 'mydb'),
        'USER': get_env_variable('DB_USER', 'myuser'),
        'PASSWORD': get_env_variable('DB_PASSWORD', 'mypassword'),
        'HOST': get_env_variable('DB_HOST', 'localhost'),
        'PORT': get_env_variable('DB_PORT', '5432'),
    }


# Password validation and hashing
PASSWORD_HASHERS = [
    'django.contrib.auth.hashers.Argon2PasswordHasher',
    'django.contrib.auth.hashers.PBKDF2PasswordHasher',
    'django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher',
    'django.contrib.auth.hashers.BCryptSHA256PasswordHasher',
]

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Autenticação com proteção Axes
AUTHENTICATION_BACKENDS = [
    'axes.backends.AxesStandaloneBackend',
    'django.contrib.auth.backends.ModelBackend',
]

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

SITE_ID = 1

# Django CKEditor 5 configuration
CKEDITOR_5_CONFIGS = {
    'default': {
        'toolbar': [
            'heading', '|',
            'bold', 'italic', 'underline', 'strikethrough', '|',
            'link', '|',
            'bulletedList', 'numberedList', 'todoList', '|',
            'outdent', 'indent', '|',
            'alignment', '|',
            'blockQuote', 'codeBlock', 'insertTable', 'imageUpload', 'mediaEmbed', '|',
            'undo', 'redo', '|',
            'sourceEditing'
        ],
        'image': {
            'toolbar': [
                'imageTextAlternative', 'imageTitle', '|',
                'imageStyle:alignLeft', 'imageStyle:alignCenter', 'imageStyle:alignRight', '|',
                'linkImage'
            ],
            'styles': ['alignLeft', 'alignCenter', 'alignRight']
        },
        'table': {
            'contentToolbar': [
                'tableColumn', 'tableRow', 'mergeTableCells',
                'tableProperties', 'tableCellProperties'
            ]
        },
        # 'language': 'en', # You can set your language here, e.g., 'pt-br'
    },
    'extends': { # This is the config_name we used for some fields
        'toolbar': [
            'heading', '|',
            'bold', 'italic', 'underline', 'strikethrough', '|',
            'link', '|',
            'bulletedList', 'numberedList', 'todoList', '|',
            'outdent', 'indent', '|',
            'alignment', '|',
            'blockQuote', 'codeBlock', 'insertTable', 'imageUpload', 'mediaEmbed', '|',
            'fontSize', 'fontFamily', 'fontColor', 'fontBackgroundColor', '|',
            'highlight', '|',
            'horizontalLine', 'pageBreak', '|',
            'specialCharacters', 'removeFormat', '|',
            'undo', 'redo', '|',
            'sourceEditing'
        ],
        'image': {
            'toolbar': [
                'imageTextAlternative', 'imageTitle', '|',
                'imageStyle:alignLeft', 'imageStyle:alignCenter', 'imageStyle:alignRight', '|',
                'linkImage'
            ],
            'styles': ['alignLeft', 'alignCenter', 'alignRight']
        },
        'table': {
            'contentToolbar': [
                'tableColumn', 'tableRow', 'mergeTableCells',
                'tableProperties', 'tableCellProperties'
            ]
        },
        # 'language': 'en', # Or your preferred language
    }
}

# Path for uploaded files relative to MEDIA_ROOT
CKEDITOR_5_UPLOAD_PATH = "uploads/"
# CKEDITOR_5_BROWSE_URL = None # Optional: URL for browsing uploaded files



# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
