# Generated by Django 5.2.3 on 2025-06-15 01:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_axes_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitesettings',
            options={'verbose_name': 'Configurações do Site', 'verbose_name_plural': 'Configurações do Site'},
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='security_settings',
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_email',
            field=models.EmailField(default='contato@meusite.com', max_length=254, verbose_name='E-mail de Contato'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='csrf_cookie_http_only',
            field=models.BooleanField(default=True, verbose_name='CSRF HTTP Only'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='csrf_cookie_secure',
            field=models.BooleanField(default=True, verbose_name='CSRF Seguro (HTTPS apenas)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='enable_2fa',
            field=models.BooleanField(default=False, verbose_name='Autenticação em Dois Fatores'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='enable_content_type_nosniff',
            field=models.BooleanField(default=True, verbose_name='X-Content-Type-Options'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='enable_hsts',
            field=models.BooleanField(default=True, help_text='HTTP Strict Transport Security', verbose_name='HSTS'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='enable_https',
            field=models.BooleanField(default=False, help_text='Redireciona todo o tráfego para HTTPS', verbose_name='Forçar HTTPS'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='enable_x_frame_options',
            field=models.BooleanField(default=True, verbose_name='X-Frame-Options'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='enable_xss_filter',
            field=models.BooleanField(default=True, verbose_name='XSS Filter'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='google_analytics_id',
            field=models.CharField(blank=True, max_length=50, verbose_name='ID do Google Analytics'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='google_site_verification',
            field=models.CharField(blank=True, max_length=255, verbose_name='Verificação do Google'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hsts_max_age',
            field=models.PositiveIntegerField(default=31536000, validators=[django.core.validators.MinValueValidator(0)], verbose_name='HSTS Max Age (segundos)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='maintenance_message',
            field=models.TextField(blank=True, verbose_name='Mensagem de Manutenção'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='password_min_length',
            field=models.PositiveIntegerField(default=8, verbose_name='Tamanho Mínimo de Senha'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='password_require_lowercase',
            field=models.BooleanField(default=True, verbose_name='Exigir Letra Minúscula'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='password_require_number',
            field=models.BooleanField(default=True, verbose_name='Exigir Número'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='password_require_special_char',
            field=models.BooleanField(default=True, verbose_name='Exigir Caractere Especial'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='password_require_uppercase',
            field=models.BooleanField(default=True, verbose_name='Exigir Letra Maiúscula'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='security_headers',
            field=models.JSONField(blank=True, default=dict, help_text='Configurações avançadas de cabeçalhos de segurança', verbose_name='Cabeçalhos de Segurança'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='seo_keywords',
            field=models.TextField(blank=True, help_text='Separadas por vírgula', verbose_name='Palavras-chave'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='session_cookie_http_only',
            field=models.BooleanField(default=True, verbose_name='HTTP Only'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='session_cookie_samesite',
            field=models.CharField(choices=[('Lax', 'Lax'), ('Strict', 'Strict'), ('None', 'None')], default='Lax', max_length=20, verbose_name='SameSite'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='session_cookie_secure',
            field=models.BooleanField(default=True, verbose_name='Sessão Segura (HTTPS apenas)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='x_frame_options',
            field=models.CharField(choices=[('DENY', 'Negar'), ('SAMEORIGIN', 'Mesma Origem')], default='DENY', max_length=20, verbose_name='X-Frame-Options'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='axes_cooloff_time',
            field=models.PositiveIntegerField(default=1, help_text='Tempo que o usuário permanece bloqueado após exceder o limite de tentativas', verbose_name='Tempo de Bloqueio (horas)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='axes_failure_limit',
            field=models.PositiveIntegerField(default=5, help_text='Número de tentativas de login malsucedidas antes do bloqueio', verbose_name='Tentativas de Login Antes do Bloqueio'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='axes_lock_out_at_failure',
            field=models.BooleanField(default=True, help_text='Bloquear imediatamente ao atingir o número máximo de tentativas', verbose_name='Bloquear ao Atingir o Limite'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='axes_only_user_failure',
            field=models.BooleanField(default=False, help_text='Se habilitado, bloqueia apenas por nome de usuário, não por IP', verbose_name='Bloquear Apenas por Usuário'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='axes_reset_on_success',
            field=models.BooleanField(default=True, help_text='Reiniciar a contagem de tentativas após um login bem-sucedido', verbose_name='Reiniciar Contador no Sucesso'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='axes_use_user_agent',
            field=models.BooleanField(default=True, help_text='Considerar o user-agent ao bloquear acessos', verbose_name='Diferenciar por Navegador'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='maintenance_mode',
            field=models.BooleanField(default=False, verbose_name='Modo Manutenção'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='seo_description',
            field=models.TextField(default='Descrição do meu site', verbose_name='Descrição SEO'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='seo_title',
            field=models.CharField(default='Meu Site - Título', max_length=255, verbose_name='Título SEO'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='site_name',
            field=models.CharField(default='Meu Site', max_length=100, verbose_name='Nome do Site'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='site_url',
            field=models.URLField(default='http://localhost:8000', verbose_name='URL do Site'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualizado em'),
        ),
    ]
