# Generated by Django 5.2.3 on 2025-06-15 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0004_migrate_security_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='csrf_cookie_secure',
            field=models.BooleanField(default=False, verbose_name='CSRF Seguro (HTTPS apenas)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='session_cookie_secure',
            field=models.BooleanField(default=False, verbose_name='Sessão Segura (HTTPS apenas)'),
        ),
    ]
