# Generated by Django 5.2.3 on 2025-06-20 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0006_backupconfig_compliancesettings_customcss_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xmlsitemap',
            name='url',
            field=models.CharField(help_text='Enter the path relative to the site, e.g., /about/ or /products/my-product/. Must start with a slash.', max_length=2000, verbose_name='URL Path'),
        ),
    ]
