# Generated by Django 5.2.3 on 2025-06-21 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0007_alter_xmlsitemap_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='favicon',
            field=models.ImageField(blank=True, help_text='Ícone exibido na aba do navegador (32x32px ou 64x64px, .ico ou .png)', null=True, upload_to='site_settings/favicons/', verbose_name='Favicon'),
        ),
    ]
